spring:
  application:
    name: msvc-course
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled:  true
    path: /docs/swagger-ui.Course