spring:
  application:
    name: msvc-user
  config:
    import: optional:configserver:http://localhost:8888
    fail-fast: true
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled:  true
    path: /docs/swagger-ui.User

jwt:
  secret: ${env.JWT_SECRET}




