eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: http://localhost:9030
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter  # APLICAMOS LOS FILTROS JWT
        - id: course
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/course/**
          filters:
            - AuthenticationFilter