server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   # El servidor no necesita registrarse a sí mismo
    fetch-registry: false         # El servidor no obtiene el registro
    server-url:
      default-zone: http://localhost:${server.port}/eureka
