eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://msvc-user
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter  # APLICAMOS LOS FILTROS JWT
        - id: course
          uri: lb://msvc-course
          predicates:
            - Path=/api/v1/course/**
          filters:
            - AuthenticationFilter
        - id: payment
          uri: lb://msvc-payment
          predicates:
            - Path=/api/v1/user-courses/**
          filters:
            - AuthenticationFilter