server:
  port: 8090

spring:
  application:
    name: msvc-course
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elearning_courses_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update  # O 'create' según tu caso
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    hostname: ec2-54-165-113-58.compute-1.amazonaws.com
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

msvc-user:
  ribbon:
    listOfServers: http://localhost:9030

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 1000