server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: ec2-35-171-28-182.compute-1.amazonaws.com
  client:
    register-with-eureka: false   # El servidor no necesita registrarse a sí mismo
    fetch-registry: false         # El servidor no obtiene el registro
    server-url:
      default-zone: http://ec2-35-171-28-182.compute-1.amazonaws.com:${server.port}/eureka
